server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&serverTimezone=UTC
    username: root
    password: 360302pxygl
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice #user服务的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos的服务端地址
#      discovery:
#        cluster-name: HZ # 配置集群名称，也就是机房位置，例如：HZ，杭州
#        namespace: 08fbb334-a389-4ad9-bb97-ddf385813cf7 #命名空间。需要填写的是id
#        ephemeral: false # 设置为非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: #eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka/

useservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则-随机

ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: # 指定对userservice这个服务饥饿加载
      - userservice
#feign:
#  client:
#    config:
#      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLevel: FULL #日志级别
feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
